sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak update --appstream
flatpak install --user flathub-beta net.lutris.Lutris//beta -y
flatpak install --user flathub io.github.prateekmedia.appimagepool  com.mattjakeman.ExtensionManager   com.github.tchx84.Flatseal net.davidotek.pupgui2  com.usebottles.bottles com.github.Matoking.protontricks com.anydesk.Anydesk      org.gnome.Firmware org.gnome.gitlab.YaLTeR.Identity org.gnome.gitlab.somas.Apostrophe  org.gabmus.whatip org.gabmus.gfeeds com.bitstower.Markets com.github.liferooter.textpieces com.rafaelmardojai.Blanket com.github.hugolabe.Wike     com.unity.UnityHub  de.lernsoftware_filius.Filius md.obsidian.Obsidian org.pitivi.Pitivi   org.desmume.DeSmuME  com.visualstudio.code-oss org.gnome.Builder    org.phoenicis.playonlinux   io.github.achetagames.epic_asset_manager    -y

flatpak install org.js.nuclear.Nuclear org.freedesktop.Sdk.Extension.dotnet com.getmailspring.Mailspring com.viber.Viber com.spotify.Client us.zoom.Zoom  com.skype.Client com.orama_interactive.Pixelorama  com.microsoft.Teams org.signal.Signal org.yuzu_emu.yuzu in.srev.guiscrcpy com.vscodium.codium com.github.unrud.VideoDownloader com.google.AndroidStudio net.meijn.onvifviewer com.jetbrains.Rider -y 

flatpak install com.visualstudio.code com.discordapp.Discord   org.videolan.VLC org.mozilla.firefox org.freecadweb.FreeCAD com.obsproject.Studio org.ardour.Ardour org.winehq.Wine org.winehq.Wine.mono org.winehq.Wine.gecko org.winehq.Wine.DLLs.dxvk org.blender.Blender org.inkscape.Inkscape org.godotengine.Godot com.valvesoftware.Steam  com.github.libresprite.LibreSprite com.heroicgameslauncher.hgl cc.arduino.arduinoide org.octave.Octave org.kde.cantor org.kicad.KiCad org.kde.kdenlive org.gnome.Evolution  com.github.PintaProject.Pinta com.github.wwmm.pulseeffects de.haeckerfelix.Fragments org.gnome.Platform.Compat.i386 org.freedesktop.Platform.GL32.default org.freedesktop.Platform.GL.default -y
